# Generated from grpc/reflection/v1/reflection.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from protobuf import DescService

from . import reflection_pb
from .reflection_pb import ServerReflectionRequest, ServerReflectionResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class ServerReflection(Protocol):
    """"""
    def server_reflection_info(self, request: AsyncIterator[ServerReflectionRequest], ctx: RequestContext[ServerReflectionRequest, ServerReflectionResponse]) -> AsyncIterator[ServerReflectionResponse]:
        """
        The reflection service is structured as a bidirectional stream, ensuring
        all related requests go to a single server.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in reflection_pb.desc().services if s.type_name == 'grpc.reflection.v1.ServerReflection')

class ServerReflectionASGIApplication(ConnectASGIApplication[ServerReflection]):
    def __init__(
        self,
        service: ServerReflection | AsyncGenerator[ServerReflection],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/grpc.reflection.v1.ServerReflection/ServerReflectionInfo": Endpoint.bidi_stream(
                    method=MethodInfo(
                        name="ServerReflectionInfo",
                        service_name="grpc.reflection.v1.ServerReflection",
                        input=ServerReflectionRequest,
                        output=ServerReflectionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.server_reflection_info,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/grpc.reflection.v1.ServerReflection"


class ServerReflectionClient(ConnectClient):
    """"""
    def server_reflection_info(
        self,
        request: AsyncIterator[ServerReflectionRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AsyncIterator[ServerReflectionResponse]:
        """
        The reflection service is structured as a bidirectional stream, ensuring
        all related requests go to a single server.
        """
        return self.execute_bidi_stream(
            request=request,
            method=MethodInfo(
                name="ServerReflectionInfo",
                service_name="grpc.reflection.v1.ServerReflection",
                input=ServerReflectionRequest,
                output=ServerReflectionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class ServerReflectionSync(Protocol):
    """"""
    def server_reflection_info(self, request: Iterator[ServerReflectionRequest], ctx: RequestContext[ServerReflectionRequest, ServerReflectionResponse]) -> Iterator[ServerReflectionResponse]:
        """
        The reflection service is structured as a bidirectional stream, ensuring
        all related requests go to a single server.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in reflection_pb.desc().services if s.type_name == 'grpc.reflection.v1.ServerReflection')

class ServerReflectionWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ServerReflectionSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/grpc.reflection.v1.ServerReflection/ServerReflectionInfo": EndpointSync.bidi_stream(
                    method=MethodInfo(
                        name="ServerReflectionInfo",
                        service_name="grpc.reflection.v1.ServerReflection",
                        input=ServerReflectionRequest,
                        output=ServerReflectionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.server_reflection_info,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/grpc.reflection.v1.ServerReflection"


class ServerReflectionClientSync(ConnectClientSync):
    """"""
    def server_reflection_info(
        self,
        request: Iterator[ServerReflectionRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Iterator[ServerReflectionResponse]:
        """
        The reflection service is structured as a bidirectional stream, ensuring
        all related requests go to a single server.
        """
        return self.execute_bidi_stream(
            request=request,
            method=MethodInfo(
                name="ServerReflectionInfo",
                service_name="grpc.reflection.v1.ServerReflection",
                input=ServerReflectionRequest,
                output=ServerReflectionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
