# Generated from connectrpc/example/empty.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.4.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import TYPE_CHECKING

from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile



_DESC = file_desc(
    b'\n\x1econnectrpc/example/empty.proto\x12\x12connectrpc.example2\x0b\n\tNoMethodsb\x06proto3',
    [],
    {
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `connectrpc/example/empty.proto`."""
    return _DESC
