# Generated from connectrpc/example/empty.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES
from protobuf import DescService

from . import empty_pb

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync


class NoMethods(Protocol):
    """
    A service without any methods.
    """
    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in empty_pb.desc().services if s.type_name == 'connectrpc.example.NoMethods')

class NoMethodsASGIApplication(ConnectASGIApplication[NoMethods]):
    def __init__(
        self,
        service: NoMethods | AsyncGenerator[NoMethods],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/connectrpc.example.NoMethods"


class NoMethodsClient(ConnectClient):
    """
    A service without any methods.
    """
    pass

class NoMethodsSync(Protocol):
    """
    A service without any methods.
    """
    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in empty_pb.desc().services if s.type_name == 'connectrpc.example.NoMethods')

class NoMethodsWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: NoMethodsSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/connectrpc.example.NoMethods"


class NoMethodsClientSync(ConnectClientSync):
    """
    A service without any methods.
    """
    pass
